//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster1500.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.BookSubject = new HashSet<BookSubject>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<BookSubject> BookSubject { get; set; }
    }
}
